name: "qa"
on:
  push: 
    branches: 
      - master
  pull_request:
    branches:
      - master


jobs:
  qa:
    name: qa

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: install dependences
        run: npm ci

      - name: test and generate coverage report
        run: |
          npm test

      - name: upload test coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ github.token }}
